"use client";
import { ThemeProvider } from "next-themes";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "@/providers/ToastProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // 👇🏻 suppressHydrationWarning avoids hydration mismatches from theme flicker
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 👇🏻ThemeProvider: attribute="class" makes sure that Tailwind's dark: utilities work correctly */}
        <ThemeProvider attribute="class" defaultTheme="system">
          <ToastProvider />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
